package io.cloudflight.ci.info

enum class CIServer(val serverName: String) {
    APPCENTER("Visual Studio App Center"),
    APPCIRCLE("Appcircle"),
    APPVEYOR("AppVeyor"),
    AZURE_PIPELINES("Azure Pipelines"),
    BAMBOO("Bamboo"),
    BITBUCKET("Bitbucket Pipelines"),
    BITRISE("Bitrise"),
    BUDDY("Buddy"),
    BUILDKITE("Buildkite"),
    CIRCLE("CircleCI"),
    CIRRUS("Cirrus CI"),
    CODEBUILD("AWS CodeBuild"),
    CODEFRESH("Codefresh"),
    CODEMAGIC("Codemagic"),
    CODESHIP("Codeship"),
    DRONE("Drone"),
    DSARI("dsari"),
    EAS("Expo Application Services"),
    GITHUB_ACTIONS("GitHub Actions"),
    GITLAB("GitLab CI"),
    GOCD("GoCD"),
    HUDSON("Hudson"),
    JENKINS("Jenkins"),
    LAYERCI("LayerCI"),
    MAGNUM("Magnum CI"),
    NETLIFY("Netlify CI"),
    NEVERCODE("Nevercode"),
    RENDER("Render"),
    SAIL("Sail CI"),
    SCREWDRIVER("Screwdriver"),
    SEMAPHORE("Semaphore"),
    SHIPPABLE("Shippable"),
    SOLANO("Solano CI"),
    STRIDER("Strider CD"),
    TASKCLUSTER("TaskCluster"),
    TEAMCITY("TeamCity"),
    TRAVIS("Travis CI"),
    VERCEL("Vercel"),
    WOODPECKER("Woodpecker"),
    XCODE_CLOUD("Xcode Cloud"),
    XCODE_SERVER("Xcode Server"),
}
